/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CarroDAO;
import database.Utilitarios;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Carro;

/**
 *
 * @author Alunos
 */
public class JFramecadastroCarro extends javax.swing.JFrame {

    /**
     * Creates new form JFramecadastroCarro
     */
    public JFramecadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroupQuantidadePortas = new javax.swing.ButtonGroup();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jComboBoxCor = new javax.swing.JComboBox();
        jLabelAnoFabricacao = new javax.swing.JLabel();
        jSpinnerAnoFabricação = new javax.swing.JSpinner();
        jLabelAnoLancamento = new javax.swing.JLabel();
        jSpinnerAnoLancamento = new javax.swing.JSpinner();
        jLabeltipoPneu = new javax.swing.JLabel();
        jTextFieldTipoPneu = new javax.swing.JTextField();
        jLabelQuantidadeBatidas = new javax.swing.JLabel();
        jTextFieldQuantidadeBatidas = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelFabricante = new javax.swing.JLabel();
        jTextFieldFabricante = new javax.swing.JTextField();
        jLabelPlaca = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelChassi = new javax.swing.JLabel();
        jTextFieldChassi = new javax.swing.JTextField();
        jLabelQuilometragem = new javax.swing.JLabel();
        jTextFieldQuilometragem = new javax.swing.JTextField();
        jLabelPotencia = new javax.swing.JLabel();
        jTextFieldPotencia = new javax.swing.JTextField();
        jLabelDataCompra = new javax.swing.JLabel();
        jTextFieldDataCompra = new javax.swing.JTextField();
        jLabelEstaFuncional = new javax.swing.JLabel();
        jComboBoxEstaFuncional = new javax.swing.JComboBox();
        jLabelPermitidaCirculacao = new javax.swing.JLabel();
        jRadioButtonPermitidaCirculacaooSim = new javax.swing.JRadioButton();
        jRadioButtonPermitidaCirculacaooNao = new javax.swing.JRadioButton();
        jLabelQuantidadePortas = new javax.swing.JLabel();
        jRadioButtonQuantidadePortas2 = new javax.swing.JRadioButton();
        jRadioButtonQuantidadePortas4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPaneDescricao = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelRenavam = new javax.swing.JLabel();
        jTextFieldRenavam = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de carro");

        jLabelNome.setText("nome");

        jLabelCor.setText("cor");

        jComboBoxCor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branco\t", "Prata\t", "Preto\t", "Cinza", "Vermelho", "Azul", "Bege", "Verde" }));

        jLabelAnoFabricacao.setText("Ano Fabricacao");

        jLabelAnoLancamento.setText("anoLancamento");

        jLabeltipoPneu.setText("Tipo Pneu");

        jLabelQuantidadeBatidas.setText("Quantidade de Batidas");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelFabricante.setText("Fabricante");

        jTextFieldFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFabricanteActionPerformed(evt);
            }
        });

        jLabelPlaca.setText("Placa");

        jLabelChassi.setText("Chassi");

        jLabelQuilometragem.setText("Quilometragem");

        jLabelPotencia.setText("Potencia");

        jTextFieldPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPotenciaActionPerformed(evt);
            }
        });

        jLabelDataCompra.setText("Data Compra");

        jTextFieldDataCompra.setToolTipText("");

        jLabelEstaFuncional.setText("Esta Funcional");

        jComboBoxEstaFuncional.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        jComboBoxEstaFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstaFuncionalActionPerformed(evt);
            }
        });

        jLabelPermitidaCirculacao.setText("Permitida Circulacao");

        jRadioButtonPermitidaCirculacaooSim.setText("Sim");
        jRadioButtonPermitidaCirculacaooSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPermitidaCirculacaooSimActionPerformed(evt);
            }
        });

        jRadioButtonPermitidaCirculacaooNao.setText("Não");

        jLabelQuantidadePortas.setText("quantidade de Portas");

        buttonGroupQuantidadePortas.add(jRadioButtonQuantidadePortas2);
        jRadioButtonQuantidadePortas2.setText("2");

        buttonGroupQuantidadePortas.add(jRadioButtonQuantidadePortas4);
        jRadioButtonQuantidadePortas4.setText("4");

        jLabel2.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPaneDescricao.setViewportView(jTextAreaDescricao);

        jLabel3.setText("Código");

        jLabelRenavam.setText("Renavam");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCor)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAnoFabricacao)
                                    .addComponent(jLabelAnoLancamento)
                                    .addComponent(jLabeltipoPneu)
                                    .addComponent(jLabelPotencia))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome)
                                    .addComponent(jTextFieldPotencia)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSpinnerAnoFabricação)
                                            .addComponent(jSpinnerAnoLancamento))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQuantidadeBatidas)
                                    .addComponent(jLabelPlaca)
                                    .addComponent(jLabelQuilometragem)
                                    .addComponent(jLabelFabricante)
                                    .addComponent(jLabelChassi)
                                    .addComponent(jLabelDataCompra)
                                    .addComponent(jLabelQuantidadePortas)
                                    .addComponent(jLabelEstaFuncional)
                                    .addComponent(jLabelPermitidaCirculacao))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTipoPneu)
                                    .addComponent(jTextFieldQuantidadeBatidas)
                                    .addComponent(jTextFieldFabricante)
                                    .addComponent(jTextFieldPlaca)
                                    .addComponent(jTextFieldChassi)
                                    .addComponent(jTextFieldQuilometragem)
                                    .addComponent(jTextFieldDataCompra)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonQuantidadePortas2)
                                                .addGap(51, 51, 51)
                                                .addComponent(jRadioButtonQuantidadePortas4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBoxEstaFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonPermitidaCirculacaooSim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonPermitidaCirculacaooNao)))
                                        .addGap(0, 71, Short.MAX_VALUE))
                                    .addComponent(jTextFieldRenavam))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPaneDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelRenavam))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor)
                            .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnoFabricacao)
                            .addComponent(jSpinnerAnoFabricação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnoLancamento)
                            .addComponent(jSpinnerAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTipoPneu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltipoPneu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadeBatidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantidadeBatidas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFabricante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChassi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQuilometragem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantidadePortas)
                            .addComponent(jRadioButtonQuantidadePortas2)
                            .addComponent(jRadioButtonQuantidadePortas4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataCompra)
                            .addComponent(jTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonPermitidaCirculacaooSim)
                                .addComponent(jRadioButtonPermitidaCirculacaooNao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPermitidaCirculacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEstaFuncional)
                                    .addComponent(jComboBoxEstaFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRenavam)
                            .addComponent(jTextFieldRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonExcluir))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPotenciaActionPerformed

    private void jComboBoxEstaFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstaFuncionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstaFuncionalActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Carro meuCarro = new Carro();

        meuCarro.setNome(jTextFieldNome.getText());

        meuCarro.setAnoFabricacao(Short.parseShort(jSpinnerAnoFabricação.getValue().toString()));

        meuCarro.setAnoLancamento(Short.parseShort(jSpinnerAnoLancamento.getValue().toString()));
        
        meuCarro.setTipoPneu(Short.parseShort(jTextFieldTipoPneu.getText()));
        
        meuCarro.setPotencia(Short.parseShort(jTextFieldPotencia.getText()));
        
        meuCarro.setQuantidadeBatidas(Byte.parseByte(jTextFieldQuantidadeBatidas.getText()));
        
        meuCarro.setFabricante(jTextFieldFabricante.getText());
        
        meuCarro.setPlaca(jTextFieldPlaca.getText());
        
        meuCarro.setChassi(jTextFieldChassi.getText());
        
        meuCarro.setQuilometragem(Float.parseFloat(jTextFieldQuilometragem.getText()));
        
        meuCarro.setDescricao(jTextAreaDescricao.getText());
        
        meuCarro.setRenavam(Integer.parseInt(jTextFieldRenavam.getText()));

        String dataCompra = jTextFieldDataCompra.getText();

        int ano = Integer.parseInt(dataCompra.substring(6, 10));
        int mes = Integer.parseInt(dataCompra.substring(3, 5));
        int dia = Integer.parseInt(dataCompra.substring(0, 2));
        meuCarro.setDataCompra(new Date(ano, mes, dia));

        byte quantidadePortas = jRadioButtonQuantidadePortas2.isSelected()
                ? (byte) 2 : (byte) 4;
        meuCarro.setQuantidadePortas(quantidadePortas);

        meuCarro.setEstaFuncional(jComboBoxEstaFuncional.getSelectedIndex() == 0);

        meuCarro.setPermitidaCirculacao(jRadioButtonPermitidaCirculacaooSim.isSelected());

        meuCarro.setCor(String.valueOf(jComboBoxCor.getSelectedItem()));

        CarroDAO dao = new CarroDAO();
        if (!jLabelCodigo.getText().equals("")) {
            meuCarro.setId(Integer.parseInt(jLabelCodigo.getText()));
            int codigo = dao.alterar(meuCarro);
            if (codigo != Utilitarios.NAO_FOI_POSSIVEL_ALTERAR) {
                JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possivel alterar");
            }
        } else {
            int codigo = dao.inserir(meuCarro);
            if (codigo != Utilitarios.NAO_FOI_POSSIVEL_INSERIR) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                jLabelCodigo.setText(String.valueOf(codigo));
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possivel inserir");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFabricanteActionPerformed

    private void jRadioButtonPermitidaCirculacaooSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPermitidaCirculacaooSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPermitidaCirculacaooSimActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if(jLabelCodigo.getText().equals("")){
            
        }else{
            int codigo = Integer.parseInt(jLabelCodigo.getText());
            CarroDAO dao = new CarroDAO();
            if(dao.excluir(codigo) == Utilitarios.NAO_FOI_POSSIVEL_EXCLUIR){
                JOptionPane.showMessageDialog(null,"Não foi possivel excluir");
            }else{
                JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                dispose();
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramecadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramecadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramecadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramecadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramecadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupQuantidadePortas;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCor;
    private javax.swing.JComboBox jComboBoxEstaFuncional;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAnoFabricacao;
    private javax.swing.JLabel jLabelAnoLancamento;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelDataCompra;
    private javax.swing.JLabel jLabelEstaFuncional;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPermitidaCirculacao;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelQuantidadeBatidas;
    private javax.swing.JLabel jLabelQuantidadePortas;
    private javax.swing.JLabel jLabelQuilometragem;
    private javax.swing.JLabel jLabelRenavam;
    private javax.swing.JLabel jLabeltipoPneu;
    private javax.swing.JRadioButton jRadioButtonPermitidaCirculacaooNao;
    private javax.swing.JRadioButton jRadioButtonPermitidaCirculacaooSim;
    private javax.swing.JRadioButton jRadioButtonQuantidadePortas2;
    private javax.swing.JRadioButton jRadioButtonQuantidadePortas4;
    private javax.swing.JScrollPane jScrollPaneDescricao;
    private javax.swing.JSpinner jSpinnerAnoFabricação;
    private javax.swing.JSpinner jSpinnerAnoLancamento;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldDataCompra;
    private javax.swing.JTextField jTextFieldFabricante;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldPotencia;
    private javax.swing.JTextField jTextFieldQuantidadeBatidas;
    private javax.swing.JTextField jTextFieldQuilometragem;
    private javax.swing.JTextField jTextFieldRenavam;
    private javax.swing.JTextField jTextFieldTipoPneu;
    // End of variables declaration//GEN-END:variables
}
